---
- Media:
    - Request something:
        icon: seerr.png
        href: http://master.local:5055
        description: Seerr
        siteMonitor: http://home-gateway:5055
        server: local
        container: home-seerr

    - Watch something:
        icon: jellyfin.png
        href: http://master.local:8096
        description: Jellyfin
        siteMonitor: http://home-gateway:8096
        server: local
        container: home-jellyfin

    - System state (WSL2):
        icon: glances.png
        href: http://master.local:61208
        description: Glances
        siteMonitor: http://home-glances:61208
        server: local
        container: home-glances

    - Track it:
        icon: trakt.png
        href: https://trakt.tv
        description: trakt.tv
        #siteMonitor: https://trakt.tv

    - Trakt app:
        icon: trakt.png
        href: https://app.trakt.tv
        description: app.trakt.tv
        #siteMonitor: https://app.trakt.tv

    - Statistics:
        icon: jellystat.png
        href: http://master.local:3000
        description: Jellystat
        siteMonitor: http://home-gateway:3000
        server: local
        container: home-jellystat

- Management:
    - Torrents:
        icon: qbittorrent.png
        href: http://master.local:8080
        description: qBitTorrent
        siteMonitor: http://home-gateway:8080
        showStats: true
        server: local
        container: home-qbittorrent
        widget:
          type: qbittorrent
          url: http://home-gateway:8080

    - TV Shows Tracker:
        icon: sonarr.png
        href: http://master.local:8989
        description: Sonarr
        siteMonitor: http://home-gateway:8989
        server: local
        container: home-sonarr

    - Movies Tracker:
        icon: radarr.png
        href: http://master.local:7878
        description: Radarr
        siteMonitor: http://home-gateway:7878
        server: local
        container: home-radarr

    - Subtitles Downloader:
        icon: bazarr.png
        href: http://master.local:6767
        description: Bazarr
        siteMonitor: http://home-gateway:6767
        server: local
        container: home-bazarr

    - Indexers setup:
        icon: prowlarr.png
        href: http://master.local:9696
        description: Prowlarr
        siteMonitor: http://home-gateway:9696
        server: local
        container: home-prowlarr

    - Ads blocking:
        icon: adblock.png
        href: http://master.local:23002
        description: AdGuard
        siteMonitor: http://home-adguard:80/login.html
        server: local
        container: home-adguard
