---
title: Home media center
description: A collection of services to manage and enjoy media library, all running in Docker containers and orchestrated with Docker Compose.
theme: dark
color: slate

background:
  image: /images/current.jpg
  opacity: 30 # 0-100

headerStyle: boxedWidgets
showStats: false
hideVersion: true
hideGroupTitles: true
#cardBlur: xs

layout:
  Media:
    tab: Services
    style: column

  Management:
    tab: Services
    style: column

  System:
    tab: Services
    style: column

  Personal:
    tab: Bookmarks

  Services:
    tab: Bookmarks
